name: eeg-seizure-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn=1.4.2
  - imbalanced-learn=0.12.2
  - matplotlib
  - seaborn
  - mne
  - jupyter
  - ipykernel
  - requests
  - tqdm
  - pytorch-cuda
  - pytorch
  - torchaudio
  - torchvision
  - pip
  - pip:
    - pyedflib
    - wfdb
    - xgboost
    - dask
    - lightgbm
