name: eeg-seizure-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - mne
  - jupyter
  - requests
  - tqdm
  - pip
  - pip:
    - tensorflow
    - pyedflib
    - wfdb