name: eeg-seizure-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - mne
  - jupyter
  - ipykernel
  - requests
  - tqdm
  - imblearn
  - pip
  - pip:
    - tensorflow
    - pyedflib
    - wfdb