name: eeg-seizure-detention
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn=1.4.2
  - imbalanced-learn=0.12.2
  - matplotlib
  - seaborn
  - mne
  - jupyter
  - ipykernel
  - requests
  - tqdm
  - xgboost
  - dask
  - lightgbm
  - pytorch
  - pytorch-cuda=11.8 # or 12.1 driver-dependent
  - torchvision
  - torchaudio
  - shap
  - lime
  - pip
  - pip:
      - pyedflib
      - wfdb